from app.models import db, playlist_songs
from sqlalchemy import insert

def seed_playlist_songs():
    # db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=5))

    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=1))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=2))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=3))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=5))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=13))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=23))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=33))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=43))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=53))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=63))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=73))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=8))
    db.session.execute(playlist_songs.insert().values(playlist_id=1, song_id=93))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=1))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=3))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=6))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=16))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=26))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=36))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=46))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=56))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=66))
    db.session.execute(playlist_songs.insert().values(playlist_id=2, song_id=76))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=11))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=21))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=31))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=41))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=51))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=61))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=71))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=81))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=91))
    db.session.execute(playlist_songs.insert().values(playlist_id=3, song_id=72))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=2))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=32))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=42))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=52))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=62))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=72))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=82))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=92))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=102))
    db.session.execute(playlist_songs.insert().values(playlist_id=4, song_id=112))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=5))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=15))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=25))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=35))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=45))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=55))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=65))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=75))
    db.session.execute(playlist_songs.insert().values(playlist_id=5, song_id=85))


    # db.session.add(playlist_song1)
    # db.session.add(playlist_song2)
    # db.session.add(playlist_song3)
    # db.session.add(playlist_song4)
    # db.session.add(playlist_song5)
    # db.session.add(playlist_song6)
    # db.session.add(playlist_song7)
    # db.session.add(playlist_song8)
    # db.session.add(playlist_song9)

    db.session.commit()


def undo_playlist_songs():
    db.session.execute('TRUNCATE playlist_songs RESTART IDENTITY CASCADE;')
    db.session.commit()
