from app.models import db, Playlist

def seed_playlists():
    library1 = Playlist(playlist_name='Library', owner_id=1)
    library2 = Playlist(playlist_name='Library', owner_id=2)
    library3 = Playlist(playlist_name='Library', owner_id=3)
    library4 = Playlist(playlist_name='Library', owner_id=4)
    library5 = Playlist(playlist_name='Library', owner_id=5)
    library6 = Playlist(playlist_name='Library', owner_id=6)
    library7 = Playlist(playlist_name='Library', owner_id=7)
    library8 = Playlist(playlist_name='Library', owner_id=8)
    library9 = Playlist(playlist_name='Library', owner_id=9)
    library10 = Playlist(playlist_name='Library', owner_id=10)
    library11 = Playlist(playlist_name='Library', owner_id=11)
    library12 = Playlist(playlist_name='Library', owner_id=12)
    library13 = Playlist(playlist_name='Library', owner_id=13)
    library14 = Playlist(playlist_name='Library', owner_id=14)
    library15 = Playlist(playlist_name='Library', owner_id=15)
    library16 = Playlist(playlist_name='Library', owner_id=16)
    playlist1 = Playlist(playlist_name='emo', owner_id=1, profile_pic='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/michael_jackson_thriller_fdy6mf.jpg')
    playlist2 = Playlist(playlist_name='bangerzz', owner_id=1, profile_pic='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg')
    playlist3 = Playlist(playlist_name='ayylmao', owner_id=1, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181495/t7zyye8h4cdy94vrrrpw.png')
    playlist4 = Playlist(playlist_name='wubwubwub', owner_id=1, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180242/wsxwc6sowcitfql8lywp.jpg')
    playlist5 = Playlist(playlist_name='yo its lit', owner_id=1, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181639/ruwsafw67rs8tcwjurlr.jpg')
    playlist6 = Playlist(playlist_name='oldskool', owner_id=2, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181729/lnvndqb9fq9rsn0wrysh.png')
    playlist7 = Playlist(playlist_name='vibes', owner_id=2, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181872/gocvlweai150d5f1v1yh.jpg')
    playlist8 = Playlist(playlist_name='wanderlust', owner_id=3, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181991/zghclhztmbqxivo5bhf9.jpg')
    playlist9 = Playlist(playlist_name='yeeeet', owner_id=3, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182154/cz6awxbbf9ohcdjinjfu.png')
    playlist10 = Playlist(playlist_name='house/eletro', owner_id=3, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183562/hdwwqjdnmuknihvmnvad.jpg')
    playlist11 = Playlist(playlist_name='chinese classics', owner_id=3, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183630/um2bhx25rohytkwwvcnv.jpg')
    playlist12 = Playlist(playlist_name='midnight raves', owner_id=4, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182967/zpvdkkefsacrthbc2z8y.jpg')
    playlist13 = Playlist(playlist_name='classics', owner_id=4, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183787/d7nmpp7sgdslf1qoeti1.jpg')
    playlist14 = Playlist(playlist_name='ganggang', owner_id=4, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183914/oy6khprofp0juwmufh50.jpg')
    playlist15 = Playlist(playlist_name='kpop', owner_id=5, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183996/ef2wgx9sdtadhb9mvswk.jpg')
    playlist16 = Playlist(playlist_name='ayylmao', owner_id=5, profile_pic='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179543/qjtf6xwadtebkqtictz6.jpg')
    playlist17 = Playlist(playlist_name='wildnouts', owner_id=6, profile_pic='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162144/poctaitpcuc2dvoipv5q.jpg')
    playlist18 = Playlist(playlist_name='kpop', owner_id=7, profile_pic='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/linkin_park_hybrid_theory_mufqc8.jpg')
    playlist19 = Playlist(playlist_name='yoooooo', owner_id=7, profile_pic='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/evanscence_fallen_qiansn.jpg')
    playlist20 = Playlist(playlist_name='dusty shoe', owner_id=7, profile_pic='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/kanye_late_registration_mbdboj.jpg')






    db.session.add(library1)
    db.session.add(library2)
    db.session.add(library3)
    db.session.add(library4)
    db.session.add(library5)
    db.session.add(library6)
    db.session.add(library7)
    db.session.add(library8)
    db.session.add(library9)
    db.session.add(library10)
    db.session.add(library11)
    db.session.add(library12)
    db.session.add(library13)
    db.session.add(library14)
    db.session.add(library15)
    db.session.add(library16)
    db.session.add(playlist1)
    db.session.add(playlist2)
    db.session.add(playlist3)
    db.session.add(playlist4)
    db.session.add(playlist5)
    db.session.add(playlist6)
    db.session.add(playlist7)
    db.session.add(playlist8)
    db.session.add(playlist9)
    db.session.add(playlist10)
    db.session.add(playlist11)
    db.session.add(playlist12)
    db.session.add(playlist13)
    db.session.add(playlist14)
    db.session.add(playlist15)
    db.session.add(playlist16)
    db.session.add(playlist17)
    db.session.add(playlist18)
    db.session.add(playlist19)
    db.session.add(playlist20)

    db.session.commit()

def undo_playlists():
    db.session.execute('TRUNCATE playlists RESTART IDENTITY CASCADE;')
    db.session.commit()
