from app.models import db, Playlist

def seed_playlists():
    library1 = Playlist(playlist_name='Library', owner_id=1)
    library2 = Playlist(playlist_name='Library', owner_id=2)
    library3 = Playlist(playlist_name='Library', owner_id=3)
    library4 = Playlist(playlist_name='Library', owner_id=4)
    library5 = Playlist(playlist_name='Library', owner_id=5)
    library6 = Playlist(playlist_name='Library', owner_id=6)
    library7 = Playlist(playlist_name='Library', owner_id=7)
    library8 = Playlist(playlist_name='Library', owner_id=8)
    library9 = Playlist(playlist_name='Library', owner_id=9)
    library10 = Playlist(playlist_name='Library', owner_id=10)
    library11 = Playlist(playlist_name='Library', owner_id=11)
    library12 = Playlist(playlist_name='Library', owner_id=12)
    library13 = Playlist(playlist_name='Library', owner_id=13)
    library14 = Playlist(playlist_name='Library', owner_id=14)
    library15 = Playlist(playlist_name='Library', owner_id=15)
    library16 = Playlist(playlist_name='Library', owner_id=16)
    playlist1 = Playlist(playlist_name='emo', owner_id=1)
    playlist2 = Playlist(playlist_name='bangerzz', owner_id=1)
    playlist3 = Playlist(playlist_name='ayylmao', owner_id=1)
    playlist4 = Playlist(playlist_name='wubwubwub', owner_id=1)
    playlist5 = Playlist(playlist_name='yo its lit', owner_id=1)
    playlist6 = Playlist(playlist_name='oldskool', owner_id=2)
    playlist7 = Playlist(playlist_name='vibes', owner_id=2)
    playlist8 = Playlist(playlist_name='wanderlust', owner_id=3)
    playlist9 = Playlist(playlist_name='yeeeet', owner_id=3)
    playlist10 = Playlist(playlist_name='house/eletro', owner_id=3)
    playlist11 = Playlist(playlist_name='chinese classics', owner_id=3)
    playlist12 = Playlist(playlist_name='midnight raves', owner_id=4)
    playlist13 = Playlist(playlist_name='classics', owner_id=4)
    playlist14 = Playlist(playlist_name='ganggang', owner_id=4)
    playlist15 = Playlist(playlist_name='kpop', owner_id=5)
    playlist16 = Playlist(playlist_name='ayylmao', owner_id=5)
    playlist17 = Playlist(playlist_name='wildnouts', owner_id=6)
    playlist18 = Playlist(playlist_name='kpop', owner_id=7)
    playlist19 = Playlist(playlist_name='yoooooo', owner_id=7)
    playlist20 = Playlist(playlist_name='dusty shoe', owner_id=7)






    db.session.add(library1)
    db.session.add(library2)
    db.session.add(library3)
    db.session.add(library4)
    db.session.add(library5)
    db.session.add(library6)
    db.session.add(library7)
    db.session.add(library8)
    db.session.add(library9)
    db.session.add(library10)
    db.session.add(library11)
    db.session.add(library12)
    db.session.add(library13)
    db.session.add(library14)
    db.session.add(library15)
    db.session.add(library16)
    db.session.add(playlist1)
    db.session.add(playlist2)
    db.session.add(playlist3)
    db.session.add(playlist4)
    db.session.add(playlist5)
    db.session.add(playlist6)
    db.session.add(playlist7)
    db.session.add(playlist8)
    db.session.add(playlist9)
    db.session.add(playlist10)
    db.session.add(playlist11)
    db.session.add(playlist12)
    db.session.add(playlist13)
    db.session.add(playlist14)
    db.session.add(playlist15)
    db.session.add(playlist16)
    db.session.add(playlist17)
    db.session.add(playlist18)
    db.session.add(playlist19)
    db.session.add(playlist20)

    db.session.commit()

def undo_playlists():
    db.session.execute('TRUNCATE playlists RESTART IDENTITY CASCADE;')
    db.session.commit()
