from app.models import db, Song, playlist_songs, Playlist


def seed_songs():
    song1 = Song(title='Billy Jean', artist='Michael Jackson', album='Thriller', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/michael_jackson_thriller_fdy6mf.jpg', genre='Pop', url='https://res.cloudinary.com/photofinder/video/upload/v1638837028/vibeful%20mp3/michael_jackson_billy_jean_lyrics_fvibrd.mp3')
    song2 = Song(title='Goddamn', artist='Tyga', album='Legendary', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047311/album%20pic/tyga_legendary_gcuono.png', genre='Rap', url='https://res.cloudinary.com/photofinder/video/upload/v1638836615/vibeful%20mp3/Tyga_-_Goddamn_Audio_x8hyne.mp3')
    song3 = Song(title='Spaceman', artist='Hardwell', album='Hardwell Presents Revealed, Volume 3', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/hardwell_presents_revealed_kd9iut.jpg', genre='EDM', url='https://res.cloudinary.com/photofinder/video/upload/v1638837618/vibeful%20mp3/Hardwell_-_Spaceman_Original_Mix_qkvpfb.mp3')
    song4 = Song(title='Welcome to My Life', artist='Simple Plan', album='Still Not Getting Any...', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/simpel_plan_still_not_getting_any_cm3ys4.jpg', genre='Rock', url='https://res.cloudinary.com/photofinder/video/upload/v1638837504/vibeful%20mp3/Welcome_to_my_life-lyrics_Full_song_ivvshi.mp3')
    song5 = Song(title='In The End', artist='Linkin Park', album='Hybrid Theory', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/linkin_park_hybrid_theory_mufqc8.jpg', genre='Rock', url='https://res.cloudinary.com/photofinder/video/upload/v1638837501/vibeful%20mp3/In_the_end_-_Linkin_Park_with_lyrics_jvzwba.mp3')
    song6 = Song(title='Bring Me To Life', artist='Evanescence', album='Fallen', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/evanscence_fallen_qiansn.jpg', genre='Rock', url='https://res.cloudinary.com/photofinder/video/upload/v1638837503/vibeful%20mp3/Evanescence-Bring_Me_To_Life_lyrics_fiywef.mp3')
    song7 = Song(title='Gold Digger', artist='Kanye West', album='Late Registration', cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/kanye_late_registration_mbdboj.jpg', genre='Rap', url='https://res.cloudinary.com/photofinder/video/upload/v1638837503/vibeful%20mp3/Kanye_West_-_Gold_Digger_feat._Jamie_Foxx_Lyrics_Video_f6vrpp.mp3')



    song8 = Song(title='Picture Me Rollin', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161509/2Pac_-_Picture_Me_Rollin_ucnz8r.mp3')
    song9 = Song(title='I Get Around', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161509/2Pac_-_Picture_Me_Rollin_ucnz8r.mp3')
    song10 = Song(title='Hit Em Up', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161509/2Pac_-_Picture_Me_Rollin_ucnz8r.mp3')
    song11 = Song(title='Dear Mama', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161509/2Pac_-_Picture_Me_Rollin_ucnz8r.mp3')
    song12 = Song(title='All Eyez On Me', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161509/2Pac_-_Picture_Me_Rollin_ucnz8r.mp3')
    song13 = Song(title='Ambitionz Az a Ridah', artist='2pac', album='All Eyez on Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Rap', url='https://res.cloudinary.com/photofinder/video/upload/v1638837503/vibeful%20mp3/Kanye_West_-_Gold_Digger_feat._Jamie_Foxx_Lyrics_Video_f6vrpp.mp3')


    song14 = Song(title='Face Down', artist='The Red Jumpsuit Apparatus', album="Don't You Fake It", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162144/poctaitpcuc2dvoipv5q.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161493/The_Red_Jumpsuit_Apparatus_Face_Down_lyrics_HD_bmkqg5.mp3')
    song15 = Song(title='Tame Impala', artist='Zhu', album='Ringos Desert', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162561/maxresdefault_cbsdke.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161490/ZHU_Tame_Impala_-_My_Life_Audio_vfyy2e.mp3')
    song16 = Song(title='Came For The Low', artist='Zhu', album='Came For The Low', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162610/j3fshahpo80618blfeae.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161484/ZHU_partywithray_-_Zhudio54_Official_Music_Video_f0b6fl.mp3')
    song17 = Song(title='Paradise Awaits', artist='Zhu', album='The Nightday', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162755/64ddb0d0424f1048b68b8fd44fdcdac4.1000x1000x1_imjust.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161483/ZHU-_Paradise_Awaits_Official_Video_tzi6mq.mp3')
    song18 = Song(title='Light It Up', artist='Zhu', album='Ringos Desert', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162889/vdmmpsurpg1xqwgcbkk6.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161481/ZHU_-_Light_It_Up_feat._TOKiMONSTA_Official_Audio_lp8yri.mp3')
    song19 = Song(title='In The Morning', artist='Zhu', album='Generationwhy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162976/350x350_kopcls.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161480/ZHU_-_In_The_Morning_kvginp.mp3')
    song20 = Song(title='Good Life', artist='Zhu', album='Generationwhy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162976/350x350_kopcls.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161478/ZHU_-_Good_Life_Audio_tllvnp.mp3')
    song21 = Song(title='Cold Blooded', artist='Zhu', album='Generationwhy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162976/350x350_kopcls.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161466/ZHU_-_Cold_Blooded_Audio_gibcsi.mp3')
    song22 = Song(title='Faded', artist='Zhu', album='Generationwhy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162976/350x350_kopcls.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161466/ZHU_-_Faded_Official_Music_Video_dwmdy7.mp3')
    song23 = Song(title='Cocaine Model', artist='Zhu', album='Generationwhy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639162976/350x350_kopcls.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161464/ZHU_-_Cocaine_Model_j4onnv.mp3')


    song24 = Song(title='Last Christmas', artist='Wham', album='Last Christmas', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639163351/f6cje3lpj0rkuuwexaqc.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161464/Wham_-_Last_Christmas_Official_Lyric_Video_ymv9lo.mp3')
    song25 = Song(title='Ocean Avenue', artist='Yellowcard', album='Ocean Avenue', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639163481/artworks-000513619599-2bhg91-t500x500_epsnvx.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161461/Yellowcard_-_Ocean_Avenue_Lyrics_mk39ni.mp3')
    song26 = Song(title='Say It Aint So', artist='Weezer', album="Opposite Sides of the Same Good Ol' Fence", cover='https://res.cloudinary.com/photofinder/image/upload/v1639047310/album%20pic/kanye_late_registration_mbdboj.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161454/Weezer_-_Say_It_Ain_t_So_otqbc7.mp3')
    song27 = Song(title='Island In The Sun', artist='Weezer', album='Late Registration', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639163766/oq9pthblqweutzyzvdv4.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161444/Weezer_-_Island_In_The_Sun_vr1zg6.mp3')

    song28 = Song(title='A Thousand Miles', artist='Vanessa Carlton', album='Legally Blonde', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164046/w4ntihhh5mg5cvrew1zq.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161443/Vanessa_Carlton_-_A_Thousand_Miles_Lyrics_gxvw6t.mp3')
    song29 = Song(title='Beverly Hills', artist='Weezer', album='Make Believe', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164072/jcu9kkpze55k39wzceuf.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161442/Weezer_-_Beverly_Hills_Lyrics_i4gvjg.mp3')
    song30 = Song(title='Check Yes Juliet', artist='We The Kings', album="We The Kings", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164248/arr089mmjwm1wzrlxxnl.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161443/We_The_Kings_-_Check_Yes_Juliet_Official_Video_xpaydw.mp3')
    song31 = Song(title='Mr. Brightside', artist='The Killers', album='Hot Fuss', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164312/ik6uqkrpxhblproeuspo.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161442/The_Killers_-_Mr._Brightside_Official_Music_Video_w0rmqe.mp3')
    song32 = Song(title='It Ends Tonight', artist='All American Regects', album='Move Along', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164415/Move_Along__28The_All-American_Rejects_album_-_cover_art_29_bzs6ln.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161436/The_All-American_Rejects_-_It_Ends_Tonight_ntmsto.mp3')
    song33 = Song(title='Black Hole Sun', artist='Soundgarden', album='Superunknown', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164599/71DYmaT6fZL._SL1500__r9oxyz.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161432/Soundgarden_Black_Hole_Sun_With_Lyrics_ehoehs.mp3')
    song34 = Song(title='Dirty Little Secret', artist='All American Rejects', album="Move Along", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639164415/Move_Along__28The_All-American_Rejects_album_-_cover_art_29_bzs6ln.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161427/The_All_American_Rejects_-_Dirty_little_secret_Lyrics_mpzltf.mp3')
    song35 = Song(title='Fat Lip', artist='Sum 41', album='All Killer No Filler', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639167874/riqfqn8kkjrtsun5u96k.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161424/Sum_41-Fat_lip_lyrics_wjbvfn.mp3')
    song36 = Song(title='Make It Bun Dem', artist='Skrillex', album='Make It Bun Dem After Hours', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639167990/dz3boxgbahwnvrfuitfj.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161416/Skrillex_Damian_Jr._Gong_Marley_-_Make_It_Bun_Dem_OFFICIAL_VIDEO_qqf1bn.mp3')
    song37 = Song(title='Scary Monsters and Nice Sprites', artist='Skrillex', album='Skrillex', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639168084/nho1i7acnoyisy2g2kpx.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161413/Skrillex_-_Scary_Monsters_And_Nice_Sprites_Official_Audio_afitkg.mp3')
    song38 = Song(title='Señorita', artist='Shawn Mendes', album="Señorita", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639168297/k9sgo18uwp5plkgqo4vz.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161412/Shawn_Mendes_Camila_Cabello_-_Se%C3%B1orita_Lyrics_hlsavc.mp3')
    song39 = Song(title='Bangarang', artist='Skrillex', album='Bangarang', cover='hhttps://res.cloudinary.com/dsxwhuvin/image/upload/v1639168397/vuiqwrbgdwe7l9sjxl3f.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161410/SKRILLEX_-_Bangarang_feat._Sirah_Official_Music_Video_h6fwuy.mp3')
    song40 = Song(title='Said The Sky', artist='Seven Lions', album='Rush Over Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639168479/bza12baty3ufagx7zbdf.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161409/Seven_Lions_x_Illenium_x_Said_The_Sky_-_Rush_Over_Me_feat._HALIENE_xsirdr.mp3')





    song41 = Song(title='First Of The Year', artist='Skrillex', album='Triple Vinyl Box Set', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639168084/nho1i7acnoyisy2g2kpx.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161409/Skrillex_-_First_Of_The_Year_Equinox_Official_Music_Video_dde7lz.mp3')
    song42 = Song(title='By Your Side', artist='Rod Wave', album="By Your Side", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639169833/artworks-wy9wkrR1A593PMyK-p3C9zQ-t500x500_l27huf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161398/Rod_Wave_-_By_Your_Side_Lyrics_psmnky.mp3')
    song43 = Song(title='Someone Else', artist='Rezz', album='Someone Else', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639169933/dt5kq0r6wuz6bswfu2cn.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161394/Rezz_Grabbitz_-_Someone_Else_Lyrics_mh6nem.mp3')

    song44 = Song(title='Lean On Me', artist='Rezz', album='Someone Else', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639169933/dt5kq0r6wuz6bswfu2cn.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161394/Rezz_fknsyd_-_Let_Me_In_Official_Video_rdqq9t.mp3')
    song45 = Song(title='Edge', artist='Rezz', album="The Silence Is Deafening", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170157/817Tul4Gx3L._SS500__vmflce.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161391/REZZ_-_Edge_lqocam.mp3')
    song46 = Song(title='Chemical Bond', artist='Rezz', album='Deathpact', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170241/xdanffci0ctxtmofxzt7.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161391/Rezz_Deathpact_-_Chemical_Bond_lqs8l0.mp3')
    song47 = Song(title='Falling', artist='Rezz', album='Beyond the Senses', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170379/pce1ggi7ldwkomkvmk2e.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161387/REZZ_-_Falling_ft._Underoath_joulb8.mp3')
    song48 = Song(title='Taste Of You', artist='Rezz', album="Spiral", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170379/pce1ggi7ldwkomkvmk2e.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161385/Rezz_-_Taste_of_You_Official_Video_ft._Dove_Cameron_imptpn.mp3')

    song49 = Song(title='I Wanna Run Away', artist='R3HAB', album='Run Away', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170733/t6ctk4v4og5vjtl9zw80.jpg', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161378/R3HAB_x_Mr_Eazi_x_Wafia_-_I_Wanna_Run_Away_Official_Lyric_Video_n8u0ay.mp3')
    song50 = Song(title='Good News', artist='Mac Miller', album='Circles', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170818/gmh90mazkwmdncahrdk3.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161376/Mac_Miller_-_Good_News_Lyrics_sdcld5.mp3')
    song51 = Song(title='ABG', artist='Quondo Rondo', album=" Life B4 Fame", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170896/nbyysj3luzeugj70auil.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161376/Quando_Rondo_-_ABG_Lyrics_lqbpbw.mp3')
    song52 = Song(title='Dont Play', artist='Polo G', album='Hall of Fame', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639170966/wastz0p0afiunnw9pzat.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161371/Polo_G_-_Don_t_Play_Official_Audio_ft._Lil_Baby_tsdrpi.mp3')
    song53 = Song(title='Misery Business', artist='Paramore', album='Riot!', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171040/bnxkpdolmyxmaih5ks1q.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161370/Paramore_-_Misery_Business_HQ_Audio_a7uvyp.mp3')
    song54 = Song(title='Numb', artist='Linken Park', album="Hybrid Theory", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171116/hkwag4jxihyir82hkpiu.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161369/Numb_Official_Music_Video_-_Linkin_Park_zogypv.mp3')
    song55 = Song(title='Shake It', artist='Metro Station', album='Metro Station', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171248/Shake_It_Metro_Station_wnpkrr.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161365/Metro_Station_-_Shake_It_HD_gvsh20.mp3')
    song56 = Song(title='LLC', artist='Money Man', album='Blockchain', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171365/x2kwaqyap1cu9njjcc6t.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161365/Money_Man_LLC_vsj9f3.mp3')
    song57 = Song(title='Angel Dust', artist='Mac Miller', album="Mac", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171428/podut2rlcusrgwvu31fd.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161358/Mac_Miller_-_Angel_Dust_hxkhse.mp3')
    song58 = Song(title='Circles', artist='Mac Miller', album='Mac', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171428/podut2rlcusrgwvu31fd.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161356/Mac_Miller_-_Circles_ivstnx.mp3')
    song59 = Song(title='Wake Up', artist='Kayzo Riot', album='KR', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171570/oso4ff8cyhgynzz5qaq0.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161354/KAYZO_RIOT_-_Wake_Up_uwpfth.mp3')
    song60 = Song(title='Jocko Good', artist='Akira The Don', album="Opposite", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171679/tohvyowudhxn0fmjo0mo.jpg', genre='Meaningwave', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161353/Jocko_Willink_-_GOOD_Motivational_Music_Meaningwave_Akira_The_Don_szx25z.mp3')
    song61 = Song(title='On Me', artist='Lil Baby', album='On Me', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171779/ignfxz2twgihjt9f7qrl.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161350/Lil_Baby_-_On_Me_inekly.mp3')
    song62 = Song(title='Super Gremlin', artist='Kodak Black', album='Hip Hop', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171857/l87znhqlkhe54vlvbcek.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161349/Kodak_Black_-_Super_Gremlin_Official_Audio_w6sobv.mp3')
    song63 = Song(title='Ambition For Cash', artist='Key Glock', album="Yellow Tape 2", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639171930/vsyrbbz2ctyr15y7jdtm.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161344/Key_Glock_-_Ambition_For_Cash_Audio_swxygw.mp3')
    song64 = Song(title='Feline', artist='Juice WRLD', album='Legends Never Die', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172006/irwjg2okbjfoffca62bm.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161340/Juice_WRLD_-_Feline_with_Polo_G_Trippie_Redd_Official_Audio_o7ag3g.mp3')
    song65 = Song(title='Rockstar In His Prime', artist='Juice WRLD', album='Legends Never Die', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172006/irwjg2okbjfoffca62bm.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161338/Juice_WRLD_-_Rockstar_In_His_Prime_Official_Audio_i739bd.mp3')
    song66 = Song(title='Are You Gonna Be My Girl', artist='Jet', album="Get Bord", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172184/sxpa9y9xdbylftgvgfdf.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161334/Jet_s_Are_You_Gonna_Be_My_Girl_with_Lyrics_kzvkpr.mp3')
    song67 = Song(title='The Middle', artist='Jimmy Eat World', album='Bleed American', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172220/od1ifrzizmjfmfwfgtpo.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161331/Jimmy_Eat_World_-_The_Middle_-_Lyrics_homjx3.mp3')
    song68 = Song(title='Good Things Fall Apart', artist='Illenium', album='Ascend', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161329/ILLENIUM_Jon_Bellion_-_Good_Things_Fall_Apart_vq35rd.mp3')
    song69 = Song(title='Enemy', artist='Imagine Dragons', album="Opposite", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172387/bkcbn1owoyojxvrhjql1.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161324/Imagine_Dragons_JID_-_Enemy_Lyrics_thfroq.mp3')
    song70 = Song(title='Paper Thin', artist='Illenium', album='Fallen Embers', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161324/ILLENIUM_Tom_DeLonge_Angels_Airwaves_-_Paper_Thin_Official_Audio_zgngyg.mp3')
    song71 = Song(title='Excision, I Prevail', artist='Illenium', album='Feel Something', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161322/ILLENIUM_Excision_I_Prevail_-_Feel_Something_Lyric_Video_tdoril.mp3')
    song72 = Song(title='Broken Ones', artist='Illenium', album="Ascend", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161319/ILLENIUM_Anna_Clendening_-_Broken_Ones_Visualizer_vzzvdd.mp3')
    song73 = Song(title='I See You', artist='Illenium', album='I See You', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161317/ILLENIUM_and_Said_the_Sky_-_I_See_You_Official_Audio_lsj0o7.mp3')
    song74 = Song(title='Blame Myself', artist='Illenium', album='Fallen Embers', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161309/ILLENIUM_and_Tori_Kelly-_Blame_Myself_Official_Audio_owf1jh.mp3')
    song75 = Song(title='Needed You', artist='Illenium', album="Awake", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161309/Illenium_-_Needed_You_ft._Dia_Frampton_ldn4et.mp3')
    song76 = Song(title='Story Of My Life', artist='Illenium', album='Story Of My Life', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161308/ILLENIUM_Sueco_-_Story_of_My_Life_feat._Trippie_Redd_Heavy_Edit_yhlu0p.mp3')

    song77 = Song(title='Nightlight', artist='Illenium', album='Fallen Embers', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161304/ILLENIUM_-_Nightlight_Official_Audio_pkot1r.mp3')
    song78 = Song(title='Crawl Outta Love', artist='Illenium', album='Awake', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639172344/xghbjmchfkybh75ufqdm.png', genre='EDM', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161303/ILLENIUM_-_Crawl_Outta_Love_feat._Annika_Wells_-_Official_Video_pxqrjv.mp3')
    song79 = Song(title='Godzilla', artist='Enimem', album="Music To Be Murdered By", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173495/kn4gqqxft10aax4u0uvf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161290/Godzilla_feat._Juice_WRLD_Official_Audio_nbfvjv.mp3')
    song80 = Song(title='Too Easy Remix', artist='Gunna', album='Too Easy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173543/awfxuxkwt4ofsrwptizr.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161289/Gunna_-_Too_Easy_Remix_feat._Future_Roddy_Ricch_Official_Audio_xmrful.mp3')
    song81 = Song(title='Heat Waves', artist='Glass Animals', album='Dream Land', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173690/h51iyj383xwsvxgp3c5h.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161288/Glass_Animals_-_Heat_Waves_Lyric_video_u2czbo.mp3')
    song82 = Song(title='The Anthem', artist='Good Charlotte', album='The Young and the Hopeless', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173750/sehnic7fqlgkr1j5mszi.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161286/Good_Charlotte-_The_Anthem_Lyrics_qc8gxd.mp3')
    song83 = Song(title='Rap God', artist='Eninem', album="Opposite", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173495/kn4gqqxft10aax4u0uvf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161282/Eminem_-_Rap_God_Audio_zxfknw.mp3')
    song84 = Song(title='abcdefu', artist='Gayle', album='abcdefu', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173927/axral94js2gaqk1hlhwb.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161272/GAYLE_-_abcdefu_Lyrics_csoahd.mp3')
    song85 = Song(title='Thnks fr the Mmrs ', artist='Fall Out Boy', album='Infinity on High', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173986/xg11fvwxf2wzmnstahmk.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161271/Fall_Out_Boy_-_Thanks_For_The_Memories_lyrics_with_song_epo3ab.mp3')
    song86 = Song(title='Sugar Were Going Down', artist='Fall Out Boy', album='From Under the Cork Tree', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173986/xg11fvwxf2wzmnstahmk.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161271/Fall_Out_Boy_-_Sugar_We_re_Going_Down_With_Lyrics_HQ_shib5d.mp3')
    song87 = Song(title='Mockingbird', artist='Eminem', album="Encore", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173495/kn4gqqxft10aax4u0uvf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161271/Eminem_-_Mockingbird_Lyrics_oj2ktm.mp3')
    song88 = Song(title='Not Afraid', artist='Eninem', album='Not Afraid', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173495/kn4gqqxft10aax4u0uvf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161270/Eminem_-_Not_Afraid_Lyrics_HD_uxlgox.mp3')
    song89 = Song(title='Lose Yourself', artist='Eminem', album='Encore', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639173495/kn4gqqxft10aax4u0uvf.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161260/Eminem_-_Lose_Yourself_Lyrics_pncwdz.mp3')
    song90 = Song(title='Shape Of You', artist='Ed Sheeran', album='Shape Of You', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639174386/j3zfmduus6qing6zyyfv.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161257/Ed_Sheeran_-_Shape_of_You_Lyrics_fvqlua.mp3')
    song91 = Song(title='Shivers', artist='Ed Sheeran', album="Shape Of You", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639174386/j3zfmduus6qing6zyyfv.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161254/Ed_Sheeran_-_Shivers_Lyrics_o9ieyw.mp3')
    song92 = Song(title='Cold Heart', artist='Elton John', album='The Lockdown Sessions', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639174527/oya9frbgfbvwqoxhjjmt.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161253/Elton_John_Dua_Lipa_-_Cold_Heart_Lyrics_PNAU_Remix_hr81te.mp3')
    song93 = Song(title='Knife Talk', artist='Drake', album='Certified Lover Boy', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639163766/oq9pthblqweutzyzvdv4.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161250/Drake_-_Knife_Talk_Audio_ft._21_Savage_Project_Pat_kaanck.mp3')
    song94 = Song(title='Every Chance I Get', artist='Dj Khaled', album='Khaled Khaled', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639174732/tgqcqhjugpchbj6dt1jr.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161250/DJ_Khaled_-_EVERY_CHANCE_I_GET_Official_Music_Video_ft._Lil_Baby_Lil_Durk_tdbktn.mp3')
    song95 = Song(title='Family Ties', artist='Baby Keen', album="The Melodic Blue", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639174831/hprbophem1nxyngqzerq.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161237/Baby_Keem_Kendrick_Lamar_-_family_ties_Lyrics_b6i4fa.mp3')
    song96 = Song(title='Girl All The Bad Guys Want', artist='Bowling For Soup', album='Drunk Enough To Dance', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175036/220px-GirlAllTheBadGuysWant2_v1xwkh.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161236/Bowling_For_Soup_-_Girl_All_The_Bad_Guys_Want_Official_Video_xy8vaw.mp3')
    song97 = Song(title='The Great Escape', artist='Boys Like Girls', album='Boys Like Girls', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175088/k0niwvsggshzfbodsajr.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161236/Boys_Like_Girls_-_The_Great_Escape_kmdvdt.mp3')
    song98 = Song(title='Show Me How To Live', artist='Audioslave', album="Opposite", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175141/slofr0r50kwiayybfaa8.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161235/Audioslave_-_Show_Me_How_To_Live_p78kib.mp3')
    song99 = Song(title='Like A Stone', artist='Audioslave', album='Opposite', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175141/slofr0r50kwiayybfaa8.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161231/Audioslave_-_Like_a_Stone_Lyrics_hw2n5q.mp3')
    song100 = Song(title='Cochise Lyrics', artist='Audioslave', album='Opposite', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175141/slofr0r50kwiayybfaa8.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161230/Audioslave_Cochise_lyrics_b3es33.mp3')
    song101 = Song(title='Easy On Me', artist='Adele', album="30", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175513/kfzjz23hvcgr92bghojw.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161219/Adele_-_Easy_On_Me_Lyrics_yfiohn.mp3')
    song102 = Song(title='Do It Do It', artist='Acraze', album='Do It Do It', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175576/ieva8vwmzswfshmibut2.jpg', genre='Pop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161219/ACRAZE_-_Do_It_To_It_Ft._Cherish_ap4j0m.mp3')
    song103 = Song(title='Be YourSelf', artist='Audioslave', album='Opposite', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175141/slofr0r50kwiayybfaa8.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161218/Audioslave_-_Be_Yourself_lyrics_vx75kv.mp3')
    song104 = Song(title='3oh 3', artist='Dont Trust Me', album="3OH!3", cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175633/iokg8e2mxkmwplheavdl.jpg', genre='Rock', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161216/3OH_3_-_DON_T_TRUST_ME_OFFICIAL_MUSIC_VIDEO_hshft6.mp3')
    song105 = Song(title='Man In The Mirror', artist='Boogie Wit Da Hoodie', album='OG', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639175822/tubgquxg10ahzm6pfxfp.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161216/A_Boogie_Wit_da_Hoodie_-_Man_In_the_Mirror_Official_Audio_duzdg1.mp3')
    song106 = Song(title='To Live And Die In LA', artist='2pac', album='The Don Killuminati: The 7 Day Theory', cover='https://res.cloudinary.com/dsxwhuvin/image/upload/v1639161902/61snhqynKLL._SX355__o823jr.jpg', genre='Hip Hop', url='https://res.cloudinary.com/dsxwhuvin/video/upload/v1639161207/2Pac_-_To_Live_And_Die_In_L.A._md2od5.mp3')






    song107 = Song(title='Trap Queen Crankdat Remix', artist='Fetty Wap', album='Trapmix', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179013/mxtiyhpo75cqlgrwgamj.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178779/Fetty_Wap_-_Trap_Queen_Crankdat_Remix_qllknj.mp3')
    song108 = Song(title='Vanished', artist='Crystal Castles', album="Crystal Castles", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179116/iqtbjf89aczvtq4lkocq.jpg', genre='Rock', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178778/Crystal_Castles_-_Vanished_vwpjkk.mp3')
    song109 = Song(title='Save The World - Knife Party Remix', artist='Knife Party', album='KPR', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179213/iwmxyysrpgsukblye9a8.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178777/Swedish_House_Mafia_-_Save_The_World_Knife_Party_Remix_x0h817.mp3')
    song110 = Song(title='My Life Just A Gent Remix', artist='Zhu', album='Tame Impala', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179339/zhu-1_n2crrb.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178776/ZHU_Tame_Impala_-_My_Life_Just_A_Gent_Remix_ahjzaa.mp3')
    song111 = Song(title='Into The Abyss', artist='Zeds Dead x Rezz', album='Into the Abyss', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179409/nbr2d4dkzooqfl1kxod2.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178775/Zeds_Dead_x_REZZ_-_Into_The_Abyss_mkuc0b.mp3')
    song112 = Song(title='The Show Must Go On', artist='Queen', album="Bohemian Rhapsody", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179543/qjtf6xwadtebkqtictz6.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178770/The_Show_Must_Go_On_Remastered_2011_efx2pq.mp3')
    song113 = Song(title='Trampoline - Jauz Remix', artist='Jauz', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179638/js692slfcbn4rvgthdiw.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178765/SHAED_-_Trampoline_Jauz_Remix_scchz2.mp3')
    song114 = Song(title='Hex', artist='Rezz x 1788-L', album='Certain Kind of Magic', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178755/REZZ_x_1788-L_-_H_E_X_d8ni0d.mp3')
    song115 = Song(title='Your Soul Will Never Be Released', artist='Rezz x Sayer', album='Beyond the Senses', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178755/REZZ_x_Sayer_-_Your_Soul_Will_Never_Be_Released_yeoud6.mp3')
    song116 = Song(title='Hell On Earth', artist='Rezz x Yultron', album='Hell On Earth', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178755/REZZ_x_Yultron_-_Hell_on_Earth_l5kswf.mp3')
    song117 = Song(title='I Could Be Anything', artist='Rex x The Glitch Mob', album="Glitched", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178749/Rezz_Remix_-_The_Glitch_Mob_-_I_Could_Be_Anything_feat._Elohim_nflsyc.mp3')
    song118 = Song(title='The Darkest Light - Myon Club Mix', artist='Alissa Feudo', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180121/c2088685-9e10-4177-84dc-7a84c597f21c_wdn6mj.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178745/Myon_feat._Alissa_Feudo_-_The_Darkest_Light_Myon_Club_Mix_drbwfi.mp3')
    song119 = Song(title='Nuclear Bass Face', artist='NGHTMRE', album='Subtronics', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180242/wsxwc6sowcitfql8lywp.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178744/NGHTMRE_Subtronics_-_Nuclear_Bass_Face_feat._Boogie_T_id4ewg.mp3')
    song120 = Song(title='Bruises', artist='NGHTMRE', album='Grabbitz', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180349/jys5ug0vbostgloptmq7.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178737/NGHTMRE_Grabbitz_-_Bruises_Cover_Art_Video_Ultra_Music_gm03ei.mp3')
    song121 = Song(title='In The End Remix', artist='Linken Park x Tommee Profitt', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180432/yafaz52jxipj7uphrfz2.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178737/Linkin_Park_-_In_The_End_Mellen_Gi_Tommee_Profitt_Remix_Lyrics_d3g8lp.mp3')
    song122 = Song(title='Everytime', artist='Medasin', album="Opposite", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180525/qmmt2o3iqmyb6c8utkqi.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178737/Medasin_-_Everytime_feat._Naomi_Wild_fvce01.mp3')
    song123 = Song(title='Dum Dee Dum - JiKay Remix', artist='Keys N Krates', album='Live In Toronto', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180626/artworks-000307643661-fh35sd-t500x500_mqzqo2.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178729/Keys_N_Krates_-_Dum_Dee_Dum_JiKay_Remix_OFFICIAL_todt4g.mp3')


    song124 = Song(title='Aloha', artist='Mome', album='Panorama', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180879/ohvo0nijwbzi3kxkd5el.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178727/M%C3%B8me_-_Aloha_feat._Merryn_Jeann_tcjfwe.mp3')
    song125 = Song(title='Annihilation', artist='i_o & Lights', album='AM 444', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180974/650be954ba4ddc7d327243dd3f88713e.1000x1000x1_fo1vtv.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178721/i_o_Lights_-_Annihilation_Official_Lyric_Video_tvhjzl.mp3')
    song126 = Song(title='Ghost N Sharks', artist='Jauz x Ghastly', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181085/artworks-000166385173-hx1lw0-t500x500_tjmua5.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178720/Jauz_x_Ghastly_-_Ghosts_N_Sharks_yd1e98.mp3')
    song127 = Song(title='20:25', artist='Flux Pavilion x What So Not', album="20:25 (ReauBeau Remix)", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181195/g810pro7wuodijbr4swq.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178720/Flux_Pavilion_x_What_So_Not_-_20_25_feat._Chain_Gang_of_1974_paeynu.mp3')
    song128 = Song(title='Ukiyo', artist='Hermitude', album='Dark Night Sweet Light', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181393/tjpmnyhb05zh6bbtx4zl.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178718/Hermitude_-_Ukiyo_i9jwwl.mp3')
    song129 = Song(title='Headband', artist='Ganja White Night x Subtronics', album='Subtronics', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181495/t7zyye8h4cdy94vrrrpw.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178712/Ganja_White_Night_x_Subtronics_-_Headband_Music_Video_Animation_fbsdcp.mp3')
    song130 = Song(title='The One', artist='Habstrakt x NGHTMRE', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180242/wsxwc6sowcitfql8lywp.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178710/Habstrakt_-_The_One_NGHTMRE_Remix_Monstercat_EP_Release_trigol.mp3')
    song131 = Song(title='Symphony', artist='Flux Pavilion', album='Earwax', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181639/ruwsafw67rs8tcwjurlr.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178704/Flux_Pavilion_-_Symphony_feat._Layna_sntzks.mp3')
    song132 = Song(title='Crave You - Adventure Club Remix', artist='Flight Facilities', album="Ep", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181729/lnvndqb9fq9rsn0wrysh.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178702/Flight_Facilities_-_Crave_You_Adventure_Club_Dubstep_Remix_feat._Giselle_gliqbb.mp3')
    song133 = Song(title='Tear Me Apart', artist='Graves Bishu', album='Tear Me Apart', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181872/gocvlweai150d5f1v1yh.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178701/Graves_Bishu_-_Tear_Me_Apart_Official_Lyric_Video_oezlrv.mp3')
    song134 = Song(title='Neon Jungle - Lane 8 Remix', artist='CloZee', album='Neon Jungle', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181991/zghclhztmbqxivo5bhf9.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178700/CloZee_-_Neon_Jungle_Lane_8_Remix_Official_Audio_zbhkkr.mp3')
    song135 = Song(title='Coming Home - Standerwick Remix', artist='Dash Berlin', album='Ep', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182154/cz6awxbbf9ohcdjinjfu.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178697/Dash_Berlin_feat._Bo_Bruce_-_Coming_Home_STANDERWICK_Remix_uuscbd.mp3')
    song136 = Song(title='Andalusia', artist='Hammock', album='Chasing After Shadows... Living with the Ghosts', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178693/Hammock_-_Andalusia_Chasing_After_Shadows...Living_with_the_Ghosts_HQ_brmysh.mp3')
    song137 = Song(title='Lights - Goslo Remix', artist='San Holo', album="Ep", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182444/images_f6azis.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178687/San_Holo_-_Light_GOSLO_Remix_wwqead.mp3')
    song138 = Song(title='Overtime', artist='Carnage', album='Battered Bruised & Bloody', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182629/nvsfoi1dd6wx19xcnqfo.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178685/Carnage_-_Overtime_ft._Sebastian_Reynoso_KYLE_o57bga.mp3')
    song139 = Song(title='Love Sosa - RL Grimes Remix', artist='Chief Keef', album='Trapnation', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639180974/650be954ba4ddc7d327243dd3f88713e.1000x1000x1_fo1vtv.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178684/Chief_Keef_-_Love_Sosa_RL_Grime_Remix_jj8gkm.mp3')
    song140 = Song(title='Criminals', artist='Rezz x Malaa', album='Criminals', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179742/qzqfq3mnlcsiqknjtrck.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178680/REZZ_x_MALAA_-_Criminals_d3lglf.mp3')

    song150 = Song(title='Bohemian Rhapsody', artist='Queen', album='A Night at the Opera', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639179543/qjtf6xwadtebkqtictz6.jpg', genre='Rock', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178672/Queen_Bohemian_Rhapsody_Official_Video_Remastered_f2plxl.mp3')
    song151 = Song(title='Neptune', artist='Lucii', album='Neptune', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182967/zpvdkkefsacrthbc2z8y.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178670/Lucii_-_Neptune_om9an9.mp3')
    song152 = Song(title='Pursuit Of Happiness - Steve Aoki Remix', artist='Kid Cudi', album="Ep", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183074/rh2rd3k1pynldtogsx0g.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178668/Kid_Cudi_-_Pursuit_Of_Happiness_Steve_Aoki_Remix_vrzhmv.mp3')
    song153 = Song(title='On Your Mind', artist='Kaskade', album='Redux 003', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183156/718uKB60OVL._SS500__wljlki.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178662/Kaskade_-_On_Your_Mind_NINJAWERKS_seics8.mp3')
    song154 = Song(title='Save My Grave', artist='Zeds Dead', album='We Are Deadbeats (Vol. 4)', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183215/hz2vwqhmb4cs5m5y93r6.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178661/Zeds_Dead_DNMO_GG_Magree_-_Save_My_Grave_etwftn.mp3')
    song155 = Song(title='High Possible', artist='Big Gigantic', album='Brighter Future', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183336/h0gspbg9ndfpvyqham0h.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178659/Big_Gigantic_-_Highly_Possible_ft._Waka_Flocka_Flame_mzqjgg.mp3')
    song156 = Song(title='Neck and Neck', artist='Zeds Dead', album='Northern Lights', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639181495/t7zyye8h4cdy94vrrrpw.png', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178646/Zeds_Dead_-_Neck_and_Neck_ft._Dragonette_DNMO_Remix_gjk8hh.mp3')
    song157 = Song(title='What So Not', artist='Gemini', album="What So Not", cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183562/hdwwqjdnmuknihvmnvad.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178645/What_So_Not_-_Gemini_Ft._George_Maple_Ekali_Remix_ampkju.mp3')
    song158 = Song(title='Overthinker - CloZee Remix', artist='Inzo', album='Overthinker', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183630/um2bhx25rohytkwwvcnv.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178642/INZO_-_Overthinker_CloZee_Remix_cqlgqq.mp3')
    song159 = Song(title='Concrete Angel - John O Callaghan Remix', artist='Gereth Emery', album='Electric For Life Episode 110', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639182967/zpvdkkefsacrthbc2z8y.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178640/Gareth_Emery_feat._Christina_Novelli_-_Concrete_Angel_John_O_Callaghan_Remix_Garuda_q7fyki.mp3')
    song160 = Song(title='Liquid Stranger', artist='Ganja White Night', album='Criminals', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183787/d7nmpp7sgdslf1qoeti1.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178639/Ganja_White_Night_Liquid_Stranger_-_Jungle_Juice_yikcsa.mp3')
    song161 = Song(title='Dont You Worry Child', artist='Swedish House Mafia', album='Until Now', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183914/oy6khprofp0juwmufh50.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178629/Swedish_House_Mafia_-_Don_t_You_Worry_Child_LYRICS_uswwta.mp3')
    song162 = Song(title='So High', artist='Doja Cat', album='Purrr!', cover='https://res.cloudinary.com/dj0ooyycv/image/upload/v1639183996/ef2wgx9sdtadhb9mvswk.jpg', genre='EDM', url='https://res.cloudinary.com/dj0ooyycv/video/upload/v1639178628/SO_HIGH_ms5wr1.mp3')



    db.session.add(song1)
    db.session.add(song2)
    db.session.add(song3)
    db.session.add(song4)
    db.session.add(song5)
    db.session.add(song6)
    db.session.add(song7)

    db.session.add(song8)
    db.session.add(song9)
    db.session.add(song10)
    db.session.add(song11)
    db.session.add(song12)
    db.session.add(song13)

    db.session.add(song14)
    db.session.add(song15)
    db.session.add(song16)
    db.session.add(song17)
    db.session.add(song18)
    db.session.add(song19)
    db.session.add(song20)
    db.session.add(song21)
    db.session.add(song22)
    db.session.add(song23)

    db.session.add(song24)
    db.session.add(song25)
    db.session.add(song26)
    db.session.add(song27)
    db.session.add(song28)
    db.session.add(song29)
    db.session.add(song30)
    db.session.add(song31)
    db.session.add(song32)
    db.session.add(song33)
    db.session.add(song34)
    db.session.add(song35)
    db.session.add(song36)
    db.session.add(song37)
    db.session.add(song38)
    db.session.add(song39)
    db.session.add(song40)
    db.session.add(song40)
    db.session.add(song41)
    db.session.add(song42)
    db.session.add(song43)
    db.session.add(song44)
    db.session.add(song45)
    db.session.add(song46)
    db.session.add(song47)
    db.session.add(song48)
    db.session.add(song49)
    db.session.add(song50)
    db.session.add(song51)
    db.session.add(song52)
    db.session.add(song53)
    db.session.add(song54)
    db.session.add(song55)
    db.session.add(song56)
    db.session.add(song57)
    db.session.add(song58)
    db.session.add(song59)
    db.session.add(song60)
    db.session.add(song61)
    db.session.add(song62)
    db.session.add(song63)
    db.session.add(song64)
    db.session.add(song65)
    db.session.add(song66)
    db.session.add(song67)
    db.session.add(song68)
    db.session.add(song69)
    db.session.add(song70)


    db.session.add(song80)
    db.session.add(song81)
    db.session.add(song82)
    db.session.add(song83)
    db.session.add(song84)
    db.session.add(song85)
    db.session.add(song86)
    db.session.add(song87)
    db.session.add(song88)
    db.session.add(song89)
    db.session.add(song90)
    db.session.add(song91)
    db.session.add(song92)
    db.session.add(song93)
    db.session.add(song94)
    db.session.add(song95)
    db.session.add(song96)
    db.session.add(song97)
    db.session.add(song98)
    db.session.add(song99)
    db.session.add(song100)
    db.session.add(song101)
    db.session.add(song102)
    db.session.add(song103)
    db.session.add(song104)
    db.session.add(song105)
    db.session.add(song106)
    db.session.add(song107)
    db.session.add(song108)
    db.session.add(song109)
    db.session.add(song110)
    db.session.add(song111)
    db.session.add(song112)
    db.session.add(song113)
    db.session.add(song114)
    db.session.add(song115)
    db.session.add(song116)
    db.session.add(song117)
    db.session.add(song118)
    db.session.add(song119)
    db.session.add(song120)
    db.session.add(song121)
    db.session.add(song122)
    db.session.add(song123)
    db.session.add(song124)
    db.session.add(song125)
    db.session.add(song126)
    db.session.add(song127)
    db.session.add(song128)
    db.session.add(song129)
    db.session.add(song130)
    db.session.add(song131)
    db.session.add(song132)
    db.session.add(song133)
    db.session.add(song134)
    db.session.add(song135)
    db.session.add(song136)
    db.session.add(song137)
    db.session.add(song138)
    db.session.add(song139)
    db.session.add(song140)

    db.session.add(song141)
    db.session.add(song142)
    db.session.add(song143)
    db.session.add(song144)
    db.session.add(song145)
    db.session.add(song146)
    db.session.add(song147)
    db.session.add(song148)
    db.session.add(song149)
    db.session.add(song150)
    db.session.add(song151)
    db.session.add(song152)
    db.session.add(song153)
    db.session.add(song154)
    db.session.add(song155)
    db.session.add(song156)
    db.session.add(song157)
    db.session.add(song158)
    db.session.add(song159)
    db.session.add(song160)
    db.session.add(song161)
    db.session.add(song162)


    db.session.commit()




def undo_songs():
    db.session.execute('TRUNCATE songs RESTART IDENTITY CASCADE;')
    db.session.commit()
