"""added cover image

Revision ID: b23ed72dc78c
Revises: a6188ebdc1bd
Create Date: 2021-12-09 08:07:44.056862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23ed72dc78c'
down_revision = 'a6188ebdc1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('cover', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'cover')
    # ### end Alembic commands ###
