"""added playlist cover photo

Revision ID: b28f2bbb4ea6
Revises: e62608cf5f85
Create Date: 2021-12-10 15:51:14.947250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28f2bbb4ea6'
down_revision = 'e62608cf5f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('playlist_pic', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'playlist_pic')
    # ### end Alembic commands ###
