"""added song url

Revision ID: a6188ebdc1bd
Revises: dce8318c3f98
Create Date: 2021-12-06 16:57:27.354519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6188ebdc1bd'
down_revision = 'dce8318c3f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'url')
    # ### end Alembic commands ###
